# Use a imagem base do Node.js
FROM node:14.21.3-alpine

# Definindo o diretório de trabalho para o frontend
WORKDIR /var/www/html/frontend

# Copiando os arquivos do frontend para o diretório de trabalho do Node.js
COPY . .

# Instalando as dependências do projeto
RUN npm install

# Comando padrão a ser executado quando o contêiner for iniciado
CMD ["npm", "start"]

# Expondo a porta 3000 (se necessário)
EXPOSE 3000
